CREATE TABLE employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_number text UNIQUE,
    display_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz
);

CREATE TABLE employee_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES employees(id),
    value text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz
);

CREATE UNIQUE INDEX credentials_active_value_uq
    ON employee_credentials(value) WHERE disabled_at IS NULL;

CREATE UNIQUE INDEX credentials_one_active_per_employee_uq
    ON employee_credentials(employee_id) WHERE disabled_at IS NULL;

CREATE TABLE batteries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_code text NOT NULL UNIQUE,
    serial_number text,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Append-only history. Current battery state is the latest operation by id.
-- The actor is the owner of the credential; TAKE has no location.
CREATE TABLE battery_operations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battery_id bigint NOT NULL REFERENCES batteries(id),
    type text NOT NULL CHECK (type IN ('STORE', 'TAKE', 'RETURN', 'MOVE')),
    credential_id bigint NOT NULL REFERENCES employee_credentials(id),
    location text,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK ((type = 'TAKE') = (location IS NULL))
);

CREATE INDEX battery_operations_battery_idx ON battery_operations(battery_id, id DESC);
CREATE INDEX battery_operations_credential_idx ON battery_operations(credential_id);
CREATE INDEX battery_operations_location_idx ON battery_operations(location) WHERE location IS NOT NULL;
