CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode text NOT NULL,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz,
    CONSTRAINT users_barcode_key UNIQUE (barcode)
);

CREATE TABLE batteries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_code text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Append-only history. Current battery state is the latest operation by id
-- user_id is the actor; TAKE has no location
CREATE TABLE battery_operations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battery_id bigint NOT NULL REFERENCES batteries(id),
    type text NOT NULL CHECK (type IN ('STORE', 'TAKE', 'RETURN', 'MOVE')),
    user_id bigint NOT NULL REFERENCES users(id),
    location text,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK ((type = 'TAKE') = (location IS NULL))
);

CREATE INDEX battery_operations_battery_idx ON battery_operations(battery_id, id DESC);
CREATE INDEX battery_operations_location_idx ON battery_operations(location) WHERE location IS NOT NULL;
