-- DESIGN DRAFT, not a migration for the existing application.
-- Apply only in an isolated empty schema/database after model review.
-- UUIDs generated by Go; timestamps assigned on the server.
-- Confirmed by user: one battery per place; manager requested text locations.
-- Four domain tables + one technical idempotency table; no location/device tables.
BEGIN;

CREATE TABLE employees (
    id uuid PRIMARY KEY,
    personnel_number text UNIQUE CHECK (personnel_number IS NULL OR length(btrim(personnel_number)) > 0),
    display_name text NOT NULL CHECK (length(btrim(display_name)) > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz,
    CHECK (disabled_at IS NULL OR disabled_at >= created_at)
);

CREATE TABLE employee_credentials (
    id uuid PRIMARY KEY,
    employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    value text COLLATE "C" NOT NULL CHECK (length(btrim(value)) > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz,
    UNIQUE (id, employee_id),
    CHECK (disabled_at IS NULL OR disabled_at >= created_at)
);
CREATE UNIQUE INDEX credentials_active_value_uq
    ON employee_credentials(value) WHERE disabled_at IS NULL;
CREATE INDEX credentials_employee_idx ON employee_credentials(employee_id, created_at, id);
-- No unique(employee_id): several active credentials are deliberately supported.

CREATE TABLE batteries (
    id uuid PRIMARY KEY,
    inventory_code text COLLATE "C" NOT NULL UNIQUE CHECK (length(btrim(inventory_code)) > 0),
    serial_number text CHECK (serial_number IS NULL OR length(btrim(serial_number)) > 0),
    status text NOT NULL CHECK (status IN ('STORED', 'ISSUED')),
    current_location text COLLATE "C" CHECK (current_location IS NULL OR (length(current_location) > 0 AND current_location=btrim(current_location))),
    current_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    version bigint NOT NULL CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT battery_position_ck CHECK (
        (status = 'STORED' AND current_location IS NOT NULL AND current_holder_employee_id IS NULL)
        OR (status = 'ISSUED' AND current_location IS NULL AND current_holder_employee_id IS NOT NULL)
    )
);
CREATE UNIQUE INDEX batteries_one_per_location_uq ON batteries(current_location) WHERE current_location IS NOT NULL;
CREATE INDEX batteries_holder_idx ON batteries(current_holder_employee_id, id) WHERE current_holder_employee_id IS NOT NULL;
CREATE INDEX batteries_status_idx ON batteries(status, id);
-- serial_number not UNIQUE: uniqueness scope/presence has not been confirmed.

CREATE TABLE idempotency_requests (
    scope text COLLATE "C" NOT NULL CHECK (length(btrim(scope)) > 0),
    key uuid NOT NULL,
    request_hash char(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    http_status smallint CHECK ((http_status BETWEEN 200 AND 299) OR http_status IN (404,409,422)),
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (scope, key),
    CHECK ((http_status IS NULL AND response_body IS NULL)
        OR (http_status IS NOT NULL AND response_body IS NOT NULL))
);

CREATE TABLE battery_operations (
    id uuid PRIMARY KEY,
    battery_id uuid NOT NULL REFERENCES batteries(id) ON DELETE RESTRICT,
    battery_version bigint NOT NULL CHECK (battery_version > 0),
    type text NOT NULL CHECK (type IN ('STORE','TAKE','RETURN','MOVE')),
    actor_employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    credential_id uuid NOT NULL,
    source_status text CHECK (source_status IS NULL OR source_status IN ('STORED','ISSUED')),
    destination_status text NOT NULL CHECK (destination_status IN ('STORED','ISSUED')),
    source_location text COLLATE "C" CHECK (source_location IS NULL OR (length(source_location) > 0 AND source_location=btrim(source_location))),
    destination_location text COLLATE "C" CHECK (destination_location IS NULL OR (length(destination_location) > 0 AND destination_location=btrim(destination_location))),
    source_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    destination_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    device_code text COLLATE "C" CHECK (device_code IS NULL OR length(btrim(device_code)) > 0),
    request_scope text NOT NULL,
    request_key uuid NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (battery_id, battery_version),
    UNIQUE (request_scope, request_key),
    FOREIGN KEY (credential_id, actor_employee_id)
        REFERENCES employee_credentials(id, employee_id) ON DELETE RESTRICT,
    FOREIGN KEY (request_scope, request_key)
        REFERENCES idempotency_requests(scope, key) ON DELETE RESTRICT,
    CONSTRAINT operation_shape_ck CHECK (
        (type = 'STORE' AND battery_version = 1 AND source_status IS NULL AND destination_status = 'STORED'
            AND source_location IS NULL AND destination_location IS NOT NULL
            AND source_holder_employee_id IS NULL AND destination_holder_employee_id IS NULL)
        OR (type = 'TAKE' AND battery_version > 1 AND source_status IS NOT NULL AND source_status = 'STORED'
            AND destination_status = 'ISSUED' AND source_location IS NOT NULL AND destination_location IS NULL
            AND source_holder_employee_id IS NULL AND destination_holder_employee_id IS NOT NULL
            AND destination_holder_employee_id = actor_employee_id)
        OR (type = 'RETURN' AND battery_version > 1 AND source_status IS NOT NULL AND source_status = 'ISSUED'
            AND destination_status = 'STORED' AND source_location IS NULL AND destination_location IS NOT NULL
            AND source_holder_employee_id IS NOT NULL AND destination_holder_employee_id IS NULL
            AND source_holder_employee_id = actor_employee_id)
        OR (type = 'MOVE' AND battery_version > 1 AND source_status IS NOT NULL AND source_status = 'STORED'
            AND destination_status = 'STORED' AND source_location IS NOT NULL AND destination_location IS NOT NULL
            AND source_location <> destination_location
            AND source_holder_employee_id IS NULL AND destination_holder_employee_id IS NULL)
    )
);
-- UNIQUE(battery_id,battery_version) also supports backward history scans.
CREATE INDEX operations_time_idx ON battery_operations(occurred_at DESC, id DESC);
CREATE INDEX operations_actor_idx ON battery_operations(actor_employee_id, occurred_at DESC, id DESC);
CREATE INDEX operations_source_holder_idx ON battery_operations(source_holder_employee_id, occurred_at DESC, id DESC)
    WHERE source_holder_employee_id IS NOT NULL;
CREATE INDEX operations_destination_holder_idx ON battery_operations(destination_holder_employee_id, occurred_at DESC, id DESC)
    WHERE destination_holder_employee_id IS NOT NULL;
CREATE INDEX operations_source_location_idx ON battery_operations(source_location, occurred_at DESC, id DESC)
    WHERE source_location IS NOT NULL;
CREATE INDEX operations_destination_location_idx ON battery_operations(destination_location, occurred_at DESC, id DESC)
    WHERE destination_location IS NOT NULL;
CREATE INDEX operations_device_idx ON battery_operations(device_code, occurred_at DESC, id DESC) WHERE device_code IS NOT NULL;
CREATE INDEX operations_credential_idx ON battery_operations(credential_id);

-- Defense against application mistakes. Owner/superuser is a separate trust boundary.
CREATE FUNCTION reject_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'history is append-only' USING ERRCODE = '55000';
END;
$$;
CREATE TRIGGER operations_immutable BEFORE UPDATE OR DELETE ON battery_operations
    FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER operations_no_truncate BEFORE TRUNCATE ON battery_operations
    FOR EACH STATEMENT EXECUTE FUNCTION reject_history_mutation();

CREATE FUNCTION protect_stable_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id THEN
        RAISE EXCEPTION 'id is immutable' USING ERRCODE = '55000';
    END IF;
    CASE TG_TABLE_NAME
        WHEN 'employee_credentials' THEN
            IF NEW.value IS DISTINCT FROM OLD.value OR NEW.employee_id IS DISTINCT FROM OLD.employee_id THEN
                RAISE EXCEPTION 'credential identity is immutable' USING ERRCODE='55000'; END IF;
        WHEN 'batteries' THEN
            IF NEW.inventory_code IS DISTINCT FROM OLD.inventory_code THEN
                RAISE EXCEPTION 'inventory identity is immutable' USING ERRCODE='55000'; END IF;
        ELSE NULL;
    END CASE;
    RETURN NEW;
END;
$$;
CREATE TRIGGER employees_identity BEFORE UPDATE ON employees FOR EACH ROW EXECUTE FUNCTION protect_stable_identity();
CREATE TRIGGER credentials_identity BEFORE UPDATE ON employee_credentials FOR EACH ROW EXECUTE FUNCTION protect_stable_identity();
CREATE TRIGGER batteries_identity BEFORE UPDATE ON batteries FOR EACH ROW EXECUTE FUNCTION protect_stable_identity();

-- Deferred so event and current can be written in either order within one transaction.
CREATE FUNCTION check_battery_projection() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    target_id uuid;
    current_row batteries%ROWTYPE;
    last_event battery_operations%ROWTYPE;
    previous_event battery_operations%ROWTYPE;
BEGIN
    IF TG_TABLE_NAME = 'batteries' THEN target_id := NEW.id;
    ELSE target_id := NEW.battery_id;
    END IF;
    SELECT * INTO current_row FROM batteries WHERE id = target_id;
    SELECT * INTO last_event FROM battery_operations WHERE battery_id = target_id
        ORDER BY battery_version DESC LIMIT 1;
    IF current_row.id IS NULL OR last_event.id IS NULL
        OR current_row.version IS DISTINCT FROM last_event.battery_version
        OR current_row.status IS DISTINCT FROM last_event.destination_status
        OR current_row.current_location IS DISTINCT FROM last_event.destination_location
        OR current_row.current_holder_employee_id IS DISTINCT FROM last_event.destination_holder_employee_id
        OR current_row.updated_at IS DISTINCT FROM last_event.occurred_at THEN
        RAISE EXCEPTION 'current state must match latest operation' USING ERRCODE='23514';
    END IF;
    IF TG_TABLE_NAME = 'battery_operations' THEN
      IF NEW.battery_version > 1 THEN
        SELECT * INTO previous_event FROM battery_operations
            WHERE battery_id = target_id AND battery_version = NEW.battery_version - 1;
        IF previous_event.id IS NULL
            OR NEW.source_status IS DISTINCT FROM previous_event.destination_status
            OR NEW.source_location IS DISTINCT FROM previous_event.destination_location
            OR NEW.source_holder_employee_id IS DISTINCT FROM previous_event.destination_holder_employee_id THEN
            RAISE EXCEPTION 'operation source must match previous version' USING ERRCODE='23514';
        END IF;
      END IF;
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER batteries_projection_guard AFTER INSERT OR UPDATE ON batteries
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_battery_projection();
CREATE CONSTRAINT TRIGGER operations_projection_guard AFTER INSERT ON battery_operations
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_battery_projection();

CREATE FUNCTION check_request_completed() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM idempotency_requests WHERE scope=NEW.scope AND key=NEW.key
        AND (http_status IS NULL OR response_body IS NULL)) THEN
        RAISE EXCEPTION 'request cannot commit without result' USING ERRCODE='23514';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER requests_complete_guard AFTER INSERT OR UPDATE ON idempotency_requests
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_request_completed();
CREATE FUNCTION protect_request_result() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'request retention is not configured' USING ERRCODE='55000'; END IF;
    IF OLD.http_status IS NOT NULL OR NEW.scope IS DISTINCT FROM OLD.scope OR NEW.key IS DISTINCT FROM OLD.key
        OR NEW.request_hash IS DISTINCT FROM OLD.request_hash OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'request identity and completed result are immutable' USING ERRCODE='55000';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER requests_immutable BEFORE UPDATE OR DELETE ON idempotency_requests
    FOR EACH ROW EXECUTE FUNCTION protect_request_result();
CREATE TRIGGER requests_no_truncate BEFORE TRUNCATE ON idempotency_requests
    FOR EACH STATEMENT EXECUTE FUNCTION reject_history_mutation();

COMMIT;

-- Text locations are literal historical snapshots. No location registry or FK.
-- Unique current_location protects one battery per EXACT canonical address.
-- Physical existence, spelling aliases and disabling locations are not tracked.

-- GRANTS TEMPLATE ONLY; replace roles with actual deployment roles/schema.
-- migration_owner owns tables/functions; runtime_user is NOT owner/superuser.
-- GRANT SELECT, INSERT ON battery_operations TO runtime_user;
-- GRANT SELECT, INSERT, UPDATE ON employees, employee_credentials,
--     batteries, idempotency_requests TO runtime_user;
-- No DELETE, TRUNCATE, ALTER or CREATE to runtime_user. No direct clients.
