-- Project DDL, not an applied migration. UUIDs are generated by the Go service.
-- All timestamps are timestamptz; API emits UTC RFC3339.
BEGIN;

CREATE TABLE employees (
    id uuid PRIMARY KEY,
    name varchar(200) NOT NULL CHECK (length(btrim(name)) > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE employee_credentials (
    id uuid PRIMARY KEY,
    employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    barcode varchar(128) COLLATE "C" NOT NULL UNIQUE
        CHECK (barcode ~ '^[A-Za-z0-9._:-]{1,128}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    revoked_at timestamptz,
    UNIQUE (id, employee_id),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE UNIQUE INDEX one_active_credential_per_employee
    ON employee_credentials(employee_id) WHERE revoked_at IS NULL;

CREATE TABLE cabinets (
    id uuid PRIMARY KEY,
    number integer NOT NULL UNIQUE CHECK (number > 0)
);
CREATE TABLE shelves (
    id uuid PRIMARY KEY,
    cabinet_id uuid NOT NULL REFERENCES cabinets(id) ON DELETE RESTRICT,
    number integer NOT NULL CHECK (number > 0),
    UNIQUE (cabinet_id, number)
);
CREATE TABLE cells (
    id uuid PRIMARY KEY,
    shelf_id uuid NOT NULL REFERENCES shelves(id) ON DELETE RESTRICT,
    number integer NOT NULL CHECK (number > 0),
    UNIQUE (shelf_id, number)
);

CREATE TABLE batteries (
    id uuid PRIMARY KEY,
    inventory_code varchar(128) COLLATE "C" NOT NULL UNIQUE
        CHECK (inventory_code ~ '^[A-Za-z0-9._:-]{1,128}$'),
    status varchar(16) NOT NULL CHECK (status IN ('stored', 'issued', 'lost')),
    cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    version integer NOT NULL CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT battery_position CHECK (
        (status = 'stored' AND cell_id IS NOT NULL AND holder_employee_id IS NULL)
        OR (status = 'issued' AND cell_id IS NULL AND holder_employee_id IS NOT NULL)
        OR (status = 'lost' AND cell_id IS NULL AND holder_employee_id IS NULL)
    )
);
CREATE UNIQUE INDEX one_battery_per_cell ON batteries(cell_id) WHERE cell_id IS NOT NULL;
CREATE INDEX batteries_holder ON batteries(holder_employee_id) WHERE holder_employee_id IS NOT NULL;
CREATE INDEX batteries_status_id ON batteries(status, id);

CREATE TABLE operations (
    id uuid PRIMARY KEY,
    battery_id uuid NOT NULL REFERENCES batteries(id) ON DELETE RESTRICT,
    battery_version integer NOT NULL CHECK (battery_version > 0),
    type varchar(16) NOT NULL CHECK (type IN ('register', 'checkout', 'return', 'move', 'loss')),
    actor_employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    credential_id uuid NOT NULL,
    from_cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    to_cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    from_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    to_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    reason varchar(500),
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (battery_id, battery_version),
    FOREIGN KEY (credential_id, actor_employee_id)
        REFERENCES employee_credentials(id, employee_id) MATCH FULL ON DELETE RESTRICT,
    CONSTRAINT operation_shape CHECK (
        (type = 'register' AND from_cell_id IS NULL AND to_cell_id IS NOT NULL
            AND from_holder_employee_id IS NULL AND to_holder_employee_id IS NULL
            AND reason IS NULL)
        OR (type = 'checkout' AND from_cell_id IS NOT NULL AND to_cell_id IS NULL
            AND from_holder_employee_id IS NULL AND to_holder_employee_id IS NOT NULL
            AND actor_employee_id IS NOT NULL AND actor_employee_id = to_holder_employee_id AND reason IS NULL)
        OR (type = 'return' AND from_cell_id IS NULL AND to_cell_id IS NOT NULL
            AND from_holder_employee_id IS NOT NULL AND to_holder_employee_id IS NULL
            AND reason IS NULL)
        OR (type = 'move' AND from_cell_id IS NOT NULL AND to_cell_id IS NOT NULL
            AND from_cell_id <> to_cell_id AND from_holder_employee_id IS NULL
            AND to_holder_employee_id IS NULL AND reason IS NULL)
        OR (type = 'loss' AND ((from_cell_id IS NOT NULL AND from_holder_employee_id IS NULL)
            OR (from_cell_id IS NULL AND from_holder_employee_id IS NOT NULL))
            AND to_cell_id IS NULL AND to_holder_employee_id IS NULL
            AND reason IS NOT NULL AND length(btrim(reason)) > 0)
    )
);
CREATE INDEX operations_time_id ON operations(occurred_at DESC, id DESC);
CREATE INDEX operations_battery_time ON operations(battery_id, occurred_at DESC, id DESC);
CREATE INDEX operations_actor_time ON operations(actor_employee_id, occurred_at DESC, id DESC);
CREATE INDEX operations_from_holder_time ON operations(from_holder_employee_id, occurred_at DESC, id DESC);
CREATE INDEX operations_to_holder_time ON operations(to_holder_employee_id, occurred_at DESC, id DESC);
CREATE INDEX operations_from_cell_time ON operations(from_cell_id, occurred_at DESC, id DESC);
CREATE INDEX operations_to_cell_time ON operations(to_cell_id, occurred_at DESC, id DESC);
CREATE INDEX operations_credential ON operations(credential_id);

-- Reservation rows with null response are never committed; they exist only
-- inside a command transaction and are filled before COMMIT.
CREATE TABLE idempotency_records (
    key varchar(128) COLLATE "C" PRIMARY KEY CHECK (key ~ '^[A-Za-z0-9._:-]{1,128}$'),
    request_hash char(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    http_status smallint CHECK (http_status IN (200, 201)),
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK ((http_status IS NULL AND response_body IS NULL)
        OR (http_status IS NOT NULL AND response_body IS NOT NULL))
);

COMMIT;
