-- Target demonstration schema, not an upgrade migration for the existing prototype.
-- Apply only to a fresh isolated schema/database. UUIDs are generated by the client service.
BEGIN;

CREATE TABLE employees (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 200),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz
);
CREATE TABLE employee_credentials (
    id uuid PRIMARY KEY,
    employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    value text COLLATE "C" NOT NULL UNIQUE
        CHECK (length(value) BETWEEN 1 AND 128 AND value !~ '[[:space:][:cntrl:]]'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    revoked_at timestamptz,
    UNIQUE (id, employee_id),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX credentials_employee ON employee_credentials(employee_id);

CREATE TABLE cabinets (
    id uuid PRIMARY KEY,
    number integer NOT NULL UNIQUE CHECK (number > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz
);
CREATE TABLE shelves (
    id uuid PRIMARY KEY,
    cabinet_id uuid NOT NULL REFERENCES cabinets(id) ON DELETE RESTRICT,
    number integer NOT NULL CHECK (number > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz,
    UNIQUE (cabinet_id, number)
);
CREATE TABLE cells (
    id uuid PRIMARY KEY,
    shelf_id uuid NOT NULL REFERENCES shelves(id) ON DELETE RESTRICT,
    number integer NOT NULL CHECK (number > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    disabled_at timestamptz,
    UNIQUE (shelf_id, number)
);
CREATE TABLE batteries (
    id uuid PRIMARY KEY,
    inventory_code text COLLATE "C" NOT NULL UNIQUE
        CHECK (length(inventory_code) BETWEEN 1 AND 128 AND inventory_code !~ '[[:space:][:cntrl:]]'),
    status text NOT NULL CHECK (status IN ('STORED','ISSUED')),
    current_cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    current_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    version integer NOT NULL CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT battery_position CHECK (
        (status='STORED' AND current_cell_id IS NOT NULL AND current_holder_employee_id IS NULL)
        OR (status='ISSUED' AND current_cell_id IS NULL AND current_holder_employee_id IS NOT NULL)
    )
);
CREATE UNIQUE INDEX one_battery_per_cell ON batteries(current_cell_id) WHERE current_cell_id IS NOT NULL;
CREATE INDEX batteries_holder ON batteries(current_holder_employee_id) WHERE current_holder_employee_id IS NOT NULL;
CREATE INDEX batteries_status_id ON batteries(status,id);

CREATE TABLE battery_operations (
    id uuid PRIMARY KEY,
    battery_id uuid NOT NULL REFERENCES batteries(id) ON DELETE RESTRICT,
    battery_version integer NOT NULL CHECK (battery_version > 0),
    type text NOT NULL CHECK (type IN ('STORE','TAKE','RETURN','MOVE')),
    actor_employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    credential_id uuid NOT NULL,
    device_code text CHECK (length(device_code) BETWEEN 1 AND 128 AND device_code !~ '[[:space:][:cntrl:]]'),
    source_cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    destination_cell_id uuid REFERENCES cells(id) ON DELETE RESTRICT,
    previous_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    new_holder_employee_id uuid REFERENCES employees(id) ON DELETE RESTRICT,
    recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (battery_id,battery_version),
    FOREIGN KEY (credential_id,actor_employee_id)
        REFERENCES employee_credentials(id,employee_id) ON DELETE RESTRICT,
    CONSTRAINT operation_shape CHECK (
        (type='STORE' AND source_cell_id IS NULL AND destination_cell_id IS NOT NULL
            AND previous_holder_employee_id IS NULL AND new_holder_employee_id IS NULL)
        OR (type='TAKE' AND source_cell_id IS NOT NULL AND destination_cell_id IS NULL
            AND previous_holder_employee_id IS NULL AND new_holder_employee_id IS NOT NULL
            AND new_holder_employee_id=actor_employee_id)
        OR (type='RETURN' AND source_cell_id IS NULL AND destination_cell_id IS NOT NULL
            AND previous_holder_employee_id IS NOT NULL AND new_holder_employee_id IS NULL
            AND previous_holder_employee_id=actor_employee_id)
        OR (type='MOVE' AND source_cell_id IS NOT NULL AND destination_cell_id IS NOT NULL
            AND source_cell_id<>destination_cell_id
            AND previous_holder_employee_id IS NULL AND new_holder_employee_id IS NULL)
    )
);
CREATE INDEX operations_time ON battery_operations(recorded_at DESC,id DESC);
CREATE INDEX operations_actor ON battery_operations(actor_employee_id,recorded_at DESC,id DESC);
CREATE INDEX operations_source ON battery_operations(source_cell_id,recorded_at DESC,id DESC);
CREATE INDEX operations_destination ON battery_operations(destination_cell_id,recorded_at DESC,id DESC);
CREATE INDEX operations_credential ON battery_operations(credential_id);

-- Defense against accidental history edits, including statements issued by the owner.
-- A database administrator can disable/drop these triggers; this is not tamper-proof storage.
CREATE FUNCTION reject_operation_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'battery_operations is append-only' USING ERRCODE = '55000';
END;
$$;
CREATE TRIGGER operation_no_update_delete
    BEFORE UPDATE OR DELETE ON battery_operations
    FOR EACH STATEMENT EXECUTE FUNCTION reject_operation_mutation();
CREATE TRIGGER operation_no_truncate
    BEFORE TRUNCATE ON battery_operations
    FOR EACH STATEMENT EXECUTE FUNCTION reject_operation_mutation();

CREATE TABLE idempotency_records (
    key text COLLATE "C" PRIMARY KEY CHECK (key ~ '^[A-Za-z0-9._:-]{1,128}$'),
    request_hash text NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    http_status smallint CHECK (http_status IN (200,201)),
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CHECK ((http_status IS NULL AND response_body IS NULL)
        OR (http_status IS NOT NULL AND response_body IS NOT NULL))
);

-- Application role: SELECT,INSERT on battery_operations; never UPDATE,DELETE,TRUNCATE.
-- Its database role must not own the schema/tables. Migration owner is separate.
-- No reservation with null response may be committed: service transaction invariant.
COMMIT;
